# Generated by Django 4.0.6 on 2022-08-09 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meomeok', '0002_rename_rest_id_menu_price_rest_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='rest_location',
            new_name='location',
        ),
        migrations.RenameModel(
            old_name='Restarunt',
            new_name='Restaurant',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='rest',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='menu_price',
            old_name='rest',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rest',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rest_star',
            new_name='star',
        ),
    ]
