# Generated by Django 4.0.6 on 2022-08-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meomeok', '0003_rename_rest_location_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='rest_id',
            new_name='restaurant_id',
        ),
        migrations.RenameField(
            model_name='restaurant',
            old_name='rest_name',
            new_name='restaurant_name',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='rest_number',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.DeleteModel(
            name='location',
        ),
    ]
