# Generated by Django 4.0.6 on 2022-08-05 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restarunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_id', models.IntegerField(default=1)),
                ('rest_name', models.CharField(max_length=30)),
                ('rest_number', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('category', models.IntegerField(default=0)),
                ('number', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=1)),
                ('user_name', models.CharField(max_length=5)),
                ('authority', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_star', models.FloatField(default=0.0)),
                ('post_date', models.DateTimeField(verbose_name='date published')),
                ('post_body', models.TextField()),
                ('rest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meomeok.restarunt')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meomeok.users')),
            ],
        ),
        migrations.CreateModel(
            name='rest_location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_axis', models.DecimalField(decimal_places=6, max_digits=9)),
                ('y_axis', models.DecimalField(decimal_places=6, max_digits=9)),
                ('rest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meomeok.restarunt')),
            ],
        ),
        migrations.CreateModel(
            name='menu_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=20)),
                ('menu_price', models.IntegerField()),
                ('rest_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meomeok.restarunt')),
            ],
        ),
    ]
