# Generated by Django 4.0.6 on 2022-08-05 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meomeok', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu_price',
            old_name='rest_id',
            new_name='rest',
        ),
        migrations.RenameField(
            model_name='rest_location',
            old_name='rest_id',
            new_name='rest',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='rest_id',
            new_name='rest',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
    ]
